///////////////// Generated by Openhipify /////////////////
#pragma once

__global__ void solve_mandelbrot(float const *real, float const *imag,
                                 int iterations, int *result);
///////////////////////////////////////////////////////////
