///////////////// Generated by Openhipify /////////////////
#pragma once

__global__ void add_vec_gpu(const int *a, const int *b, int *res,
                            const int len);
///////////////////////////////////////////////////////////
