///////////////// Generated by Openhipify /////////////////
#include "hip/hip_runtime.h"

#include "kernelOne.cl.hpp"
///////////////////////////////////////////////////////////

__global__ void vecAdd(const float *a, float *r) {
  unsigned int id = hipBlockDim_x * hipBlockIdx_x + hipThreadIdx_x;
}

__global__ void vecSub(const float *a, float *r) {
  unsigned int id = hipBlockDim_x * hipBlockIdx_x + hipThreadIdx_x;
}
