///////////////// Generated by Openhipify /////////////////
#pragma once

__global__ void vecAdd(const float *a, float *r);
__global__ void vecSub(const float *a, float *r);
///////////////////////////////////////////////////////////
