///////////////// Generated by Openhipify /////////////////
#pragma once

__global__ void dijkstragpu(float *Matrix, float *Visited, float *Min,
                            int *Index, float *Array, int *Path, float *lmat,
                            float *larr);
///////////////////////////////////////////////////////////
