///////////////// Generated by Openhipify /////////////////
#include "hip/hip_runtime.h"

#include "vecAdd.cl.hpp"
///////////////////////////////////////////////////////////

// OpenCL kernel. Each work item takes care of one element of c
__global__ void vecAdd(double *a, double *b, double *c, const unsigned int n) {
  // Get our global thread ID
  int x = hipBlockDim_x * hipBlockIdx_x + hipThreadIdx_x;
  int y = hipBlockDim_y * hipBlockIdx_y + hipThreadIdx_y;

  int i = y * 10000 + x;
  if (i < (100000000)) {
    a[i] = b[i] + c[i];
  }
}
