///////////////// Generated by Openhipify /////////////////
#include "hip/hip_runtime.h"

#include "vecAdd.cl.hpp"
///////////////////////////////////////////////////////////

// OpenCL kernel. Each work item takes care of one element of c
__global__ void vecAdd(double *a, double *b, double *c, const unsigned int n) {
  // Get our global thread ID
  int id = hipBlockDim_x * hipBlockIdx_x + hipThreadIdx_x;

  // Make sure we do not go out of bounds
  if (id < n)
    c[id] = a[id] + b[id];
}
