///////////////// Generated by Openhipify /////////////////
#pragma once

__global__ void qr(float *u_vec, float *a_mat, float *q_mat, float *p_mat,
                   float *prod_mat);
///////////////////////////////////////////////////////////
