///////////////// Generated by Openhipify /////////////////
#include "hip/hip_runtime.h"

#include "kernel.cl.hpp"
///////////////////////////////////////////////////////////

__global__ void vec_add(int *a, int *b, int *c) {
  /* Get unique id of work-item */
  int idx = hipBlockDim_x * hipBlockIdx_x + hipThreadIdx_x;
  // printf('%d ', idx);
  /* make addition for `a` and `b`, store result into `c` */
  c[idx] = a[idx] + b[idx];
}
