///////////////// Generated by Openhipify /////////////////
#ifndef __VECADD_H__
#define __VECADD_H__

__global__ void vecAdd(double *__restrict__ a, double *__restrict b,
                       double *__restrict__ c, const unsigned int n);
///////////////////////////////////////////////////////////
#endif